### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by akxcv** [akxcv/krasivo#5]
I suggest the following API:
```sh
# use the "poop" theme:
krasivo hello --theme poop
# or, shorter:
krasivo hello -t poop
```
We can also support user-defined themes and settings via a `~/.krasivorc` file or something. Example:
```yml
# ~/.krasivorc
default_theme: poodle
themes:
  poodle: :poodle: :poop:
  thoughtful_pray: :thinking_face: :pray::skin-tone-6:
```
```sh
# use "poodle" theme by default:
krasivo "no thanks"
# still able to use krasivo normally:
krasivo hey :no_good: :dog2:
```

This feature isn't that good without a selection of default themes that would be bundled with the package. And for that, I need help. Please offer your theme ideas here, if you have any.

**Comment by akxcv** [comment]
@nesaulov @past-one @0exp @nulldef
🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻
🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻

🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿
🙏🏿🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻
🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏿🙏🏻🙏🏿🙏🏿🙏🏿🙏🏿🙏🏿🙏🏻🙏🏿🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by past-one** [comment]
I guess, theme names should be as short as possible
```
dog: :dog: :dog2:
top: :100: :+1:
bad: :poop: :-1:
tea: :tea: :fire:
think: :shipit: :thinking:
```
It also could be `--list` option to dump themes with descriptions into console.

**Comment by nulldef** [comment]
I agree with @akxcv, It seems better API for it. But I guess that `--list` option is nessesary

**Comment by akxcv** [comment]
Yeah, I agree with the points you both made, but I'm most interested in theme ideas. I don't mean we should not discuss the API, I'm just trying to set the focus of our discussion.

So far, I like the :100: :+1:, :poop: :-1: themes. Not sure about :tea: :fire: (why fire, exactly?)
:shipit: :thinking: theme looks good as well, but "think" doesn't quite sound right (there's a shade of secrecy b/c of :shipit:)

**Comment by nesaulov** [comment]
I will give some ideas tomorrow

**Comment by nesaulov** [comment]
Additional to the listed above:

* 🏈 , :sports_medal: -> sports
* :wave:, :walking: -> bye
* 👍 , 🎉  ->celebration

**Comment by akxcv** [comment]
How about also having theme aliases? One could configure them like so:
```yaml
# ~/.krasivorc
default_theme: poodle
themes:
  poodle: :poodle: :poop:
  thoughtful_pray: :thinking_face: :pray::skin-tone-6:
  doggy: poodle # alias
```
